# See http://www.appveyor.com/docs/appveyor-yml for reference

#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - ps: .\build.ps1 -pack

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: artifacts/*

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy:

 - provider: GitHub
   release: $(APPVEYOR_REPO_TAG_NAME)
   auth_token:
     secure: gbdN6iXbtLTk1MiBecxRJvdoc6fR6x4AEFAQNuZ+UMR9NvQnXW12PXfd16gtGVGp
   artifact: artifacts/*
   draft: false
   prerelease: false
   on:
     appveyor_repo_tag: true

 # for pre-release versions
 - provider: NuGet
   api_key:
     secure: NiH62CvEa6ztPGnR9glvKexCL5sJStB62JcJ/8CcVJJAj7rkCzZvfN87E5xPpNd0
   artifact: /artifacts/.*\.nupkg/
   skip_symbols: false
   on:
     branch: master

 # for release versions
 - provider: NuGet
   api_key:
     secure: NiH62CvEa6ztPGnR9glvKexCL5sJStB62JcJ/8CcVJJAj7rkCzZvfN87E5xPpNd0
   artifact: /artifacts/.*\.nupkg/
   skip_symbols: false
   on:
     appveyor_repo_tag: true

